{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cereal
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cereal_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cereal/cereal_{{ version }}.tar.gz
  sha256: 59c3799ab2de7e3dc93a31c244e4fec74caf7a2e403dce97fbbc1d342e87490b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite
    - r-rlang
    - r-tibble
    - r-vctrs
  run:
    - r-base
    - r-jsonlite
    - r-rlang
    - r-tibble
    - r-vctrs

test:
  commands:
    - $R -e "library('cereal')"           # [not win]
    - "\"%R%\" -e \"library('cereal')\""  # [win]

about:
  home: https://r-lib.github.io/cereal/, https://github.com/r-lib/cereal/
  license: MIT
  summary: The 'vctrs' package provides a concept of vector prototype that can be especially
    useful when deploying models and code.  Serialize these object prototypes to 'JSON'
    so they can be used to check and coerce data in production systems, and deserialize
    'JSON' back to the correct object prototypes.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
